apiVersion: v1
kind: Service
metadata:
    name: "aspnetappaks-0e36"
    labels:
        app: "aspnetappaks-0e36"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aspnetappaks-0e36"